name: CI/CD on master
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To add version tags
      packages: write # To push docker image
      issues: write   # Semantic release to link issues
    steps:
      - uses: actions/checkout@master

      - name: Replace SendGrid token
        run: |
          cat ./example/mailrelay.json
          sed -i 's/_SENDGRID_API_KEY_/${{ secrets.SENDGRID_API_KEY }}/' ./example/mailrelay.json
          cat ./example/mailrelay.json

      - uses: homecentr/action-build-docker-image@feat/v1
        with:
          imageName: "homecentr/mailrelay"
          dockerHubUserName: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASSWORD }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}