name: CI/CD on master
on:
  push:

jobs:
  build:
    uses: homecentr/docker-workflows/.github/workflows/docker-image-ci-cd.yml@feat/v1
    with:
      imageName: homecentr/mailrelay
      MAIL_FROM: ${{ secrets.MAIL_FROM }}
      MAIL_TO: ${{ secrets.MAIL_TO }}
    secrets: inherit