name: CI/CD on master
on:
  push:

jobs:
  build:
    uses: homecentr/docker-workflows/.github/workflows/docker-image-ci-cd.yml@feat/v1
    with:
      imageName: homecentr/mailrelay
    secrets: inherit 